### ISSUE TITLE
Resolve combat rounds

### ISSUE THREAD

**Issue by cboveda** [cboveda/ProjectYOMI#2]
### Tasks
- [x] Implement GameData to store round number, player health, and player actions
- [x] Update UI to submit actions to GameData
- [x] Add resolution text to UI
- [x] Read and clear player inputs
- [x] Determine round outcome
- [x] Display round outcome
- [x] Update player health
